name: oddsly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  
  # Google Sign In
  google_sign_in: ^6.3.0
  
  # Apple Sign In
  sign_in_with_apple: ^6.1.4
  
  # Crypto
  crypto: ^3.0.3
  
  # HTTP
  http: ^1.2.0
  
  # Shared Preferences
  shared_preferences: ^2.3.4
  
  # Intl for formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/