// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbsnM2EynQtznOBmZa75oDdMENWdYO-J4',
    appId: '1:933573173889:ios:f7e9887c87c6c4dc892380',
    messagingSenderId: '933573173889',
    projectId: 'oddsly-f9fba',
    storageBucket: 'oddsly-f9fba.firebasestorage.app',
    iosBundleId: 'com.zharkynismagulov.oddsly',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIvzWZjEX1fTgjzHAiaMC8ADmw7MSyT_I',
    appId: '1:933573173889:web:8538f3dcf6b2f89e892380',
    messagingSenderId: '933573173889',
    projectId: 'oddsly-f9fba',
    authDomain: 'oddsly-f9fba.firebaseapp.com',
    storageBucket: 'oddsly-f9fba.firebasestorage.app',
    measurementId: 'G-GTTX7XH89K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbsnM2EynQtznOBmZa75oDdMENWdYO-J4',
    appId: '1:933573173889:ios:f7e9887c87c6c4dc892380',
    messagingSenderId: '933573173889',
    projectId: 'oddsly-f9fba',
    storageBucket: 'oddsly-f9fba.firebasestorage.app',
    iosBundleId: 'com.zharkynismagulov.oddsly',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs845h724RquZYjkNLySDzciBsmgmSuKg',
    appId: '1:933573173889:android:cc1d2c2e43094a82892380',
    messagingSenderId: '933573173889',
    projectId: 'oddsly-f9fba',
    storageBucket: 'oddsly-f9fba.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIvzWZjEX1fTgjzHAiaMC8ADmw7MSyT_I',
    appId: '1:933573173889:web:cd46dd39d0217df4892380',
    messagingSenderId: '933573173889',
    projectId: 'oddsly-f9fba',
    authDomain: 'oddsly-f9fba.firebaseapp.com',
    storageBucket: 'oddsly-f9fba.firebasestorage.app',
    measurementId: 'G-655LB0Z76F',
  );

}